name: "🐞 Bug Report"
description: "Report a bug to help us improve Tech6Sense."
title: "Bug: "
labels: [bug, needs review]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the necessary details to help us reproduce and resolve the bug as quickly as possible.

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "🔎 Description of the Bug"
      description: "Provide a clear and concise description of the bug, including where it occurs."
      placeholder: "The bug occurs when..."

  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "List the steps required to reproduce the bug."
      placeholder: "1. Go to...\n2. Click on...\n3. Observe the error..."

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "✔️ Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "I expected the module to..."

  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "❌ Actual Behavior"
      description: "Explain what actually happened instead."
      placeholder: "Instead of the expected behavior..."

  - type: textarea
    id: screenshots
    attributes:
      label: "📷 Screenshots or Logs"
      description: "Attach any relevant screenshots or logs that might help in diagnosing the issue."
      placeholder: "Attach any images or logs here."
      validations:
        required: false

  - type: dropdown
    id: browsers
    attributes:
      label: "🌐 Browser(s)"
      description: "Select the browser(s) where you experienced the issue."
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        
  - type: checkboxes
    id: checklist
    attributes:
      label: "✔️ Checklist"
      options:
        - label: "I have confirmed this bug exists in the latest version."
          required: true
        - label: "I have checked existing issues to avoid duplicates."
          required: true
        - label: "I have read and understood the [Tech6Sense Contributing Guidelines](https://github.com/Parnab03/Tech6Sense/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I have reviewed the [Code of Conduct](https://github.com/Parnab03/Tech6Sense/blob/main/CODE_OF_CONDUCT.md) and agree to abide by it."
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: "📝 Additional Notes (Optional)"
      description: "Provide any other relevant information that could help in resolving the issue."
      placeholder: "Add any extra details here."
    validations:
      required: false
